version: '3.1'
services:
  stats-server:
    build: stats/stats-server
    image: stats
    container_name: stats_container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      -  SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/postgres

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot

  ewm-service:
    build: main
    image: main
    container_name: main_container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
    #    - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5433/ewm-main-db
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-main-db

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      #- "6542:5433"
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm-main-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iaroot