drop table endpoint_hit;
drop table view_stats;

CREATE TABLE IF NOT EXISTS endpoint_hit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    app VARCHAR(255) NOT NULL,
    uri VARCHAR(255) NOT NULL,
    ip VARCHAR(20) NOT NULL,
    timestamp_endpoint VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS view_stats (
    app_view VARCHAR(255) NOT NULL,
    uri_view VARCHAR(255) NOT NULL,
    hits INTEGER
);
