--drop table category;

CREATE TABLE IF NOT EXISTS users (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name                VARCHAR(255) NOT NULL,
    email               VARCHAR(255) NOT NULL,
    CONSTRAINT uq_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS category (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name_category       VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS locations (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    lat                 FLOAT,
    lon                 FLOAT
);

CREATE TABLE IF NOT EXISTS events
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    annotation          VARCHAR(500),
    category_id         BIGINT,
    confirmed_requests  BIGINT,
    created_on          TIMESTAMP WITH TIME ZONE,
    description         TEXT,
    event_date          TIMESTAMP WITH TIME ZONE,
    initiator_id        BIGINT,
    location_id         BIGINT,
    paid                BOOLEAN,
    participant_limit   BIGINT,
    published_on        TIMESTAMP WITH TIME ZONE,
    request_moderation  BOOLEAN,
    state               VARCHAR(120),
    title               VARCHAR(120),
    views               BIGINT,
    CONSTRAINT EVENTS_CATEGORIES_ID_FK
        FOREIGN KEY (category_id)
            REFERENCES category (id) ON DELETE CASCADE,
    CONSTRAINT EVENTS_LOCATIONS_ID_FK
        FOREIGN KEY (location_id)
            REFERENCES locations (ID) ON DELETE CASCADE,
    CONSTRAINT EVENTS_USERS_ID_FK
        FOREIGN KEY (initiator_id)
            REFERENCES USERS (ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS request
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    created   TIMESTAMP WITH TIME ZONE,
    event     BIGINT,
    requester BIGINT,
    status    VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS compilations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    pinned BOOLEAN,
    title  VARCHAR(550),
    CONSTRAINT uq_compilation_title UNIQUE (title)
);

CREATE TABLE IF NOT EXISTS compilations_events
(
    event_id       BIGINT,
    compilation_id BIGINT,
    CONSTRAINT fk_to_compilations
        FOREIGN KEY (compilation_id) REFERENCES compilations (id),
    CONSTRAINT fk_to_events
        FOREIGN KEY (event_id) REFERENCES events (id)
);
